### ISSUE TITLE
Cannot download from https://www.ltehmonitor.com/

### ISSUE THREAD

**Issue by aaron-neal** [LTEHMonitor/LTEHMonitor.github.io#1]
Hi,

I am trying to test out this software but the new https://www.ltehmonitor.com/ site download section appears not to be working. No download begins.

I cannot find any form of communication advertised on the site, i.e. email, twitter so am leaving this issue here in the hope you may be able to resolve the issue.

Many Thanks.

**Comment by 0oga83** [comment]
Hi
LTE H-Monitor can be downloaded here : http://download.ltehmonitor.com
Contact : ltehmonitor (at) gmail.com

**Comment by aaron-neal** [comment]
It is odd, something wasn't working properly until I used chrome Incognito mode. I have just managed to download it now, thanks.
